CREATE TABLE coffee
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    coffee_doses INTEGER,
    milk_doses   INTEGER,
    sugar_packs  INTEGER,
    cream        BOOLEAN,
    selected     BOOLEAN,
    CONSTRAINT pk_coffee PRIMARY KEY (id)
);